### ISSUE TITLE
Parser doesn't support interfaces or headers

### ISSUE THREAD

**Issue by dselman** [bafolts/plantuml-code-generator#10]
Parser doesn't parse:

header
<font color=red>DRAFT</font>
Authors: xxx
Version: 0.1
endheader

Or:

interface Type {
    +URI getIdentifier()
}

I tried to update the parser but it looks like the peg-update script is missing?

**Comment by bafolts** [comment]
https://github.com/bafolts/plantuml-code-generator/blob/master/package.json#L9

An `npm install` should rebuild the pegjs file. 

```
node node_modules/pegjs/bin/pegjs src/plantuml.pegjs src/plantuml.js
```
should manually do it. If you can't get it working let me know. Could be something strange with it. The pegjs should take `src/plantuml.pegjs` and output to `src/plantuml.js`

**Comment by dselman** [comment]
Thanks, I got the plantuml.js to update. Now I need to add support for header, interface and !include (somehow)... I also fixed an issue with a missing Aggregation.js file.

**Comment by bafolts** [comment]
Cool. Interface shouldn't be too bad, you can leverage what is there for class. For some of the languages you wont have an interface to output and you can omit it. If you make a PR I can check it out.

**Comment by jupe** [comment]
I've implemented alternative tool which partially based on this project but have some extra features, including `header` and `interface` supports:
https://github.com/jupe/puml2code

**Comment by bafolts** [comment]
Interface will work in 0.1.2 if the output language supports interfaces.
