### ISSUE TITLE
Opposite Way

### ISSUE THREAD

**Issue by JimTheMan** [bafolts/plantuml-code-generator#11]
Hi, I see this converts plantUML files to TypeScript (well, TypScript is what I care about right now 👍 )

But I'm looking for something that will go the other way, taking a TypeScript class and converting it into PlantUML file...

**Comment by bafolts** [comment]
That shouldn't be too difficult. Would be nice to be able to take a large typescript (or java) project and generate a UML diagram. I have never dug into the internals of typescript but the tool would just have to find every class and public function and write the UML syntax, shouldn't be too complicated. If I have time during the holidays I can take a shot at this, or feel free to create a pull request.

**Comment by JimTheMan** [comment]
what, you are going to build your own tool that converts typescript into plantUML?? :)

I would think there is something that does that out there already, but I can't find anything. :/

**Comment by arwenvaughan** [comment]
There are existing libraries for single languages. Plantuml-depend for java, NPlant for C#, and perhaps one or two for other languages. It is built into some continuous integration applications as well, but not all languages in one peice of software...that I can find anyway. So, this would be spectacular if it was built. I would love to use it on the free planttext.com website as a free service.

**Comment by bafolts** [comment]
If there is none specifically for typescript I can look into it, can name it TPlant or something. I may make it a separate repository as it is opposite of the goals of this project. Guessing it shouldn't be too hard to write with a spin-off of `tslint` which already examines class structure.

**Comment by JimTheMan** [comment]
@bafolts yes that would be awesome if you could. Let me know if you make a new repo. :)

**Comment by bafolts** [comment]
I have created (started) `tplant` which supports typescript. For now it generated a sample basic class I posted as a starting point. Plan on improving it from here. Can move issues to `tplant`.

https://github.com/bafolts/tplant
