### ISSUE TITLE
Class relations not fully supported

### ISSUE THREAD

**Issue by arwenvaughan** [bafolts/plantuml-code-generator#2]
It appears some less commonly used class relationship syntax is not fully supported and returns an error of "Error parsing input file: ". I don't know node.js well but it appears the error object does not display a detailed error message about the problem that was thrown in the parser routine. Should more verbose error messaging be concatenated to the right of the colon?  Onc example case is the use of -down-, -up-, -left-, and -right- in relationship text...like...

class Dwelling {
  +Int Windows()
  +void LockTheDoor()
}
class Apartment
Dwelling <|-down- Apartment: Inheritance

**Comment by bafolts** [comment]
Will add support for `-up-`, `-down-`, `-right-`, `-left-` in the extension.

**Comment by bafolts** [comment]
https://github.com/bafolts/plantuml-code-generator/blob/master/tests/car.pegjs#L36-L39

Support added for directional descriptions inside arrows added.
