### ISSUE TITLE
AccessType is not working in templates

### ISSUE THREAD

**Issue by rwecho** [bafolts/plantuml-code-generator#31]
{{this.getAccessType}}  return empty in templates.

**Comment by GillisWerrebrouck** [comment]
It seems as if `+` (public), `-` (private) and `#` (protected) in the UML all lead to private when generating the code in typescript (and possibly other languages as well). I assume this AccessType is the root cause of this bug.

**Comment by GillisWerrebrouck** [comment]
Is there an update on when/if this bug will be resolved soon?

**Comment by bafolts** [comment]
I see these bugs coming in. Trying to find time to work on them. If this only has to be fixed for typescript at first that would help limit the scope and get the fix out faster. I can do fix for typescript only at first. This project is mostly just me and a few other contributors that have shown up over the years. It seems that recently this project has gained in popularity so I plan on spending more of my free time on improvements like this.
