### ISSUE TITLE
Property name and type are reversed in Typescript

### ISSUE THREAD

**Issue by GillisWerrebrouck** [bafolts/plantuml-code-generator#38]
UML:
```
@startuml
    class SomeClass {
        - someValue string
    }
@enduml
```

Generated code:
```
class SomeClass {
  private string : someValue;
}
```

Expected code:
```
class SomeClass {
  private someValue : string;
}
```

**Comment by bafolts** [comment]
I am not that familiar with plant UML. Examples from [here](https://plantuml.com/class-diagram) list the type first and the name second. This generator is assuming the type is listed first in plant UML.

**Comment by GillisWerrebrouck** [comment]
My apologies, it should indeed be first the type and then the name. I'll close this issue.
