### ISSUE TITLE
plantuml-code-generator can't handle comments

### ISSUE THREAD

**Issue by sruehl** [bafolts/plantuml-code-generator#8]
Following plant file fails:
```
  @startuml
  ' this is a comment
  class A
  class B
  A --|> B
  @enduml
```

with message:
```
Error parsing input file: 
SyntaxError: Expected "@enduml", "abstract ", "class ", "hide empty members", "namespace ", "package ", "setpropname.*", "skinparam", "title ", [ \t], [#], [+], [-], [A-Za-z_], [\n] or [\r\n] but "'" found.
```
Tested with upstream code

**Comment by bafolts** [comment]
This is probably due to the comment tag, I can fix this within the week. Will close this issue when completed.

**Comment by bafolts** [comment]
This should be fixed by

https://github.com/bafolts/plantuml-code-generator/commit/d085f96fd760ebfc4be5d2f73cab5754ec069e6d

**Comment by bafolts** [comment]
I added an integration test with the sample file you provided. You should be good to go. Thanks for the help.
